backend:
  image:
    pullPolicy: Never
frontend:
  image:
    pullPolicy: Never

secrets:
  # Using local in-cluster postgres service
  databaseUrl: "postgresql://todo_user:todo_password@todo-release-postgres:5432/todo_db"
  betterAuthSecret: "changeme_shared_secret_12345iqraabdullah"
  # Using real Gemini API Key from environment
  geminiApiKey: "AIzaSyAapiUAF5fzDW-PkFp9ZP-2NoRuAV_SK5s"
  